question_20: question_20.o readline.o
			gcc -o question_20 question_20.o readline.o

question_20.o: question_20.c readline.h readline.c
			gcc -c question_20.c

readline.o: readline.c readline.h
			gcc -c readline.c