question_23: question_23.o readline.o
			gcc -o question_23 question_23.o readline.o

question_23.o: question_23.c readline.h readline.c
			gcc -c question_23.c

readline.o: readline.c readline.h
			gcc -c readline.c