question_21: question_21.o readline.o
			gcc -o question_21 question_21.o readline.o

question_21.o: question_21.c readline.h readline.c
			gcc -c question_21.c

readline.o: readline.c readline.h
			gcc -c readline.c