question_25: question25.o readline.o
			gcc -o question25 question25.o readline.o

question_25.o: question25.c readline.h readline.c
			gcc -c question25.c

readline.o: readline.c readline.h
			gcc -c readline.c