question_22: question_22.o readline.o
			gcc -o question_22 question_22.o readline.o

question_22.o: question_22.c readline.h readline.c
			gcc -c question_22.c

readline.o: readline.c readline.h
			gcc -c readline.c