question_24: question24.o readline.o
			gcc -o question24 question24.o readline.o

question_24.o: question24.c readline.h readline.c
			gcc -c question24.c

readline.o: readline.c readline.h
			gcc -c readline.c