question_24: question_24.o readline.o
			gcc -o question_24 question_24.o readline.o

question_24.o: question_24.c readline.h readline.c
			gcc -c question_24.c

readline.o: readline.c readline.h
			gcc -c readline.c