question_23: question_26.o readline.o
			gcc -o question_26 question_26.o readline.o

question_23.o: question_26.c readline.h readline.c
			gcc -c question_26.c

readline.o: readline.c readline.h
			gcc -c readline.c