question_23: question_25.o readline.o
			gcc -o question_25 question_25.o readline.o

question_23.o: question_25.c readline.h readline.c
			gcc -c question_25.c

readline.o: readline.c readline.h
			gcc -c readline.c